IMPORT_PATH = '/app/input_data'
EXPORT_DAILY_FILE_HEADER = [
    'Time',
    'InverterSN',
    'Data LoggerSN',
    'Alert Details',
    'Alert Code',
    'DC Voltage PV1(V)',
    'DC Voltage PV2(V)',
    'DC Current1(A)',
    'DC Current2(A)',
    'AC Voltage R/U/A(V)',
    'AC Voltage S/V/B(V)',
    'AC Voltage T/W/C(V)',
    'AC Current R/U/A(A)',
    'AC Current S/V/B(A)',
    'AC Current T/W/C(A)',
    'AC Output Total Power (Active)(W)',
    'AC Output Frequency R(Hz)',
    'Generation of Last Month (Active)(kWh)',
    'Daily Generation (Active)(kWh)',
    'Total Generation (Active)(kWh)',
    'Power Grid Total Power(W)',
    'Power Grid Total Reactive Power(Var)',
    'Power Grid Total Apparent Power(VA)',
    'Grid Power Factor',
    'Inverter Temperature(℃)',
    'Power Limitation Percentage',
    'Power On/Off Status'
]